import type { ConsentKeyword } from "../src/lib/consent";

// How each text reads, shared by tests/consent-keywords.test.ts (the rule in
// code) and tests/consent-cache.test.ts (the same rule restated in SQL for the
// backfill), so the two are held to one list.
export const consentReplyCases: Array<[string, ConsentKeyword]> = [
  ["STOP", "REVOKE"],
  ["stop", "REVOKE"],
  [" Stop. ", "REVOKE"],
  ["STOP!!", "REVOKE"],
  ["‘STOP’", "REVOKE"],
  ["'stop'", "REVOKE"],
  ['"STOP"', "REVOKE"],
  ["“STOP”", "REVOKE"],
  ["(STOP)", "REVOKE"],
  ["*STOP*", "REVOKE"],
  ['"Stop."', "REVOKE"],
  ["[stop]", "REVOKE"],
  ["_STOP_", "REVOKE"],
  ['"START"', "GRANT"],
  ["“unstop”", "GRANT"],
  ["OPT OUT", "REVOKE"],
  ["opt-out", "REVOKE"],
  ["Opt  out", "REVOKE"],
  ["optout", "REVOKE"],
  ["REVOKE", "REVOKE"],
  ["unsubscribe", "REVOKE"],
  ["StopAll", "REVOKE"],
  ["cancel", "REVOKE"],
  ["End", "REVOKE"],
  ["quit.", "REVOKE"],
  ["unstop", "GRANT"],
  ["start", "GRANT"],
  ["START.", "GRANT"],
  // Whitespace JavaScript trims that is not ASCII: a no-break space, a byte-order mark.
  ["STOP\u00a0", "REVOKE"],
  ["opt\u00a0out", "REVOKE"],
  ["\ufeffstart", "GRANT"],
  ["please\u2028stop", "REVIEW"],
  ["yes", "YES"],
  ["Yes!", "YES"],
  // Possible stop requests in other words: a person decides.
  ["stop please", "REVIEW"],
  ["STOP PLEASE", "REVIEW"],
  ["Please stop texting me", "REVIEW"],
  ["please don't stop working on the carb", "REVIEW"],
  ["don’t text this number", "REVIEW"],
  ["Do not text me again", "REVIEW"],
  ["dont text", "REVIEW"],
  ["remove me from your list", "REVIEW"],
  ["Wrong number", "REVIEW"],
  ["I want to opt out of these", "REVIEW"],
  ["unsubscribe me", "REVIEW"],
  ["please stop texting me", "REVIEW"],
  ["I can stop by later. Also stop texting me", "REVIEW"],
  ["won't stop by, please stop", "REVIEW"],
  ["Stop. In future call me", "REVIEW"],
  ["Please stop. At this point it's harassment", "REVIEW"],
  ["stop, at once", "REVIEW"],
  ["Please stop - at this point it's harassment", "REVIEW"],
  ["Stop - in future call me", "REVIEW"],
  ["stop -- at once", "REVIEW"],
  ["stop_at once", "REVIEW"],
  ["please opt_out", "REVIEW"],
  ["please stop! Over and out", "REVIEW"],
  ["stop at once", "REVIEW"],
  ["I'll STOP  AT the shop after work", "REVIEW"],
  ["Stop\nAt this point it's harassment", "REVIEW"],
  ["Stop\nIn future call me", "REVIEW"],
  ["stop by later. also stop texting me", "REVIEW"],
  ["You won't stop texting me", "REVIEW"],
  ["you guys won't stop texting me", "REVIEW"],
  ["this number will not stop texting me", "REVIEW"],
  ["This number will not stop texting me, who is this?", "REVIEW"],
  ["it wont stop with the msgs, stop", "REVIEW"],
  ["you won't stop calling me", "REVIEW"],
  ["I said 'stop'", "REVIEW"],
  ["'stop texting me'", "REVIEW"],
  ["please stop'", "REVIEW"],
  ["I said ‘stop’ by the way", "REVIEW"],
  // Ordinary business, which must not block a thread.
  ["yesterday", "NONE"],
  ["I stopped by yesterday", "NONE"],
  ["Can I stop by Saturday to grab my bike?", "NONE"],
  ["can I stop by Saturday", "NONE"],
  ["I will stop in at 3", "NONE"],
  ["my brakes won't stop", "NONE"],
  ["stop over after work", "NONE"],
  ["I'll stop in at 3", "NONE"],
  ["can you stop over the weekend", "NONE"],
  ["my brakes won't stop the bike", "NONE"],
  ["the brakes won’t stop", "NONE"],
  ["it wont stop leaking", "NONE"],
  ["the rear wheel will not stop wobbling", "NONE"],
  ["stop by stop by", "NONE"],
  ["Can I stop by, please?", "NONE"],
  ["I'll stop\u00a0by later", "NONE"],
  ["the nonstop rattle is back", "NONE"],
  ["can I cancel my appointment?", "NONE"],
  ["pick it up at the end of the day", "NONE"],
  ["yes please", "NONE"],
  ["start the work whenever you're ready", "NONE"],
  ["", "NONE"],
];
